### ISSUE TITLE
Handling transparent PDFs and dark background colors

### ISSUE THREAD

**Issue by dsanson** [dsanson/termpdf#10]
See comments on issue #2

**Comment by dsanson** [comment]
So there are three ways to try to solve this (short of rewriting termpdf in a real programming language):
1.   Find a relatively lightweight command that will remove the transparency (or add an opaque background). It looks like [pdftk](http://linux.die.net/man/1/pdftk) can do this. And I'm sure popplerlib can do this, but I don't think poppler exposes this with any of its included command line utilities. 
2.  Use a command to change the background color _only_ in the tmux pane that displays the PDF. The relevant command is `tmux select-pane -P 'bg=white'`.
   -   this would only solve the problem when in tmux
   -   it doesn't seem to work: iTerm2's image drawing doesn't respect the tmux background color setting
3.   Temporarily change the profile for the entire iTerm session. 
   -   I don't think we can use the new [Shell Integration](http://linux.die.net/man/1/pdftk#background) features to do this---they key to directory, username, or host, not to running command.
   -   This changes the colorscheme for the whole window (not ideal when running within tmux.

**Comment by dsanson** [comment]
In the meantime, here is a function that will switch between iTerm themes from the CLI. Something like this could be integrated into termpdf, but it would require some user configuration.

``` .bash
switch_iterm_theme () {
        [[ -n $TMUX ]] && printf "\033Ptmux;\033"
        echo -e "\033]50;SetProfile=$1\a" && export ITERM_PROFILE="$1"
        [[ -n $TMUX ]] && printf "\033\\"
}
```

I have this function in my `.zshrc`, along with two aliases:

``` .bash
alias darktheme='switch_iterm_theme "Dark" && test $TMUX && tmux set -g status-bg black 2> /dev/null && tmux setw -g window-status-attr reverse'
alias lighttheme='switch_iterm_theme "Light" && test $TMUX && tmux set -g status-bg white 2> /dev/null && tmux setw -g window-status-attr default'
```

This makes it easy for me to switch between light and dark themes on the fly (the extra stuff cleans up the tmux colors to match each theme, if I run the command from within tmux).

**Comment by zhmiao** [comment]
Thanks so much for doing this! I don't use tmux, but I will try the first method.

**Comment by ghost** [comment]
I just love it when hacks work so well!

**Comment by dsanson** [comment]
Commit aaae2882715a93b2f88f83acbbf2056560800878 fixes this (as a side-effect of adding support for kitty).
