### ISSUE TITLE
Can't display one pdf

### ISSUE THREAD

**Issue by tdehaeze** [dsanson/termpdf#12]
Hi,
Thanks for the awesome hack :)
Unfortunatly, I can't make it work.

I have everything installed:
![capture d ecran 2016-11-06 11 54 02](https://cloud.githubusercontent.com/assets/10817626/20036976/df8e7776-a417-11e6-95e0-e32f8daaa79b.png)

And when I type `termpdf main.pdf`, I got this:
![capture d ecran 2016-11-06 11 54 39](https://cloud.githubusercontent.com/assets/10817626/20036977/df9059b0-a417-11e6-839a-9c4d7173d7f4.png)

I tried with several pdfs and it's always the same...

Do you have any idea why this is happening ?

Thanks

**Comment by dsanson** [comment]
That probably means that the script is not properly generating the image for that page of the PDF. Have you tried hitting "r" (refresh) or "j" (to go to the next page)?

**Comment by tdehaeze** [comment]
Yes I've tried that. Then I used your script from the branch termview and it's working :)

**Comment by duykhoa** [comment]
I also faced the same issue. I checkout the branch `termview`, and install these packages:
- `brew install poppler` (for pdfimages)
- `brew install ghostscript djvulibre`
- `brew install libtiff`
- `brew install pdfgrep`

everything works fine now 👍

**Comment by dsanson** [comment]
Curious if people are still having this problem. My memory is that I had let the script get baroque and have since cleaned it up. I think the main branch should work now.
