### ISSUE TITLE
Trying to crop throws an error

### ISSUE THREAD

**Issue by NathanielInman** [dsanson/termpdf#13]
Termpdf is awesome! Was trying to crop a pdf but it throws an error:
```
/Users/me/termpdf: line 1082: /var/folders/47/ks7rh0512gqf580snyxkzbwm0000gn/T/tmp.oWPZ3FpV/myDocName14_k2opt.pdf: No such file or directory
```
I'm able to restore the original setting by hitting `c` again.
Did go into the folder and all see in there is `myDocName14.pdf`, but nothing with the `_k2opt` added to the end.
Not sure if it's relevant but running macOS v10.12.6.
Thanks for any help!

**Comment by dsanson** [comment]
Hadn't used the cropping in a long time. Just tried it and it doesn't work for me either. I'll look into it.

**Comment by dsanson** [comment]
Should work now!
