### ISSUE TITLE
support libsixel as an output format

### ISSUE THREAD

**Issue by HalosGhost** [dsanson/termpdf#5]
[Libsixel](http://saitoha.github.com/libsixel) is an ANSI-escape compatible library that offers similar functionality to the proprietary inline image format as now used by iTerm2.

It offers true inlining (instead of the GUI hack used by w3imgdisplay), and does not require X11 to function. Ideally, iTerm2 would simply have used sixel instead of creating its own preprietary format, but since it has made its choice, hopefully developers will still choose to support sixel (already implemented by many TEs).

**Comment by XVilka** [comment]
Interesting standard. Is there any comprehensive list of the terminal emulators supporting it? Something like I've done for TrueColor support: https://gist.github.com/XVilka/8346728

**Comment by HalosGhost** [comment]
I'm not sure if there is a comprehensive one, but the repo-maintainer keeps a [shortlist](https://github.com/saitoha/libsixel#terminal-requirements)

**Comment by dsanson** [comment]
I have no immediate plans to do this, as I am primarily on OSX, so for now I'm just going to focus on making this work with iTerm. But this would be cool.

**Comment by HalosGhost** [comment]
@dsanson, I am sorry to hear that, but I understand.
