### ISSUE TITLE
Does this work via ssh as well?

### ISSUE THREAD

**Issue by laktak** [dsanson/termpdf#9]

**Comment by dsanson** [comment]
I think it ought to work. You'd need install termpdf on the remote host and use iTerm on your local host. And it probably will get confused if the remote host is not running OS X (that shouldn't be a problem in principle---just that the script as written isn't smart about these things).

**Comment by dsanson** [comment]
Since the recent rewrite, it should just work, I think, if you have `termpdf` installed on the remote host, and you are running iTerm 2.9+ on your local host. But I haven't tested it.

**Comment by laktak** [comment]
Thanks for the info!
